version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - tasknet

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    networks:
      - tasknet

  mongo:
    image: mongo:6
    container_name: task-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tasknet

volumes:
  mongo-data:


networks:
  tasknet:
